# permissions for end users to view vpsiemachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpsiemachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-vpsie
    app.kubernetes.io/part-of: cluster-api-provider-vpsie
    app.kubernetes.io/managed-by: kustomize
  name: vpsiemachine-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vpsiemachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vpsiemachines/status
  verbs:
  - get
