apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VpsieCluster
metadata:
  labels:
    app.kubernetes.io/name: vpsiecluster
    app.kubernetes.io/instance: vpsiecluster-sample
    app.kubernetes.io/part-of: cluster-api-provider-vpsie
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-vpsie
  name: vpsiecluster-sample
spec:
  # TODO(user): Add fields here
