---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  # clusterNetwork:
  #   pods:
  #     cidrBlocks:
  #       - ${POD_CIDR:=172.25.0.0/16}
  #   services:
  #     cidrBlocks:
  #       - ${SERVICES_CIDR:=172.26.0.0/16}
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VpsieCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "${CLUSTER_NAME}-control-plane"

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VpsieCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  dcIdentifier: ${DC_IDENTIFIER}
  project: ${VPSEI_PROJECT}
  network:
    apiServerLoadbalancers:
      resourceIdentifier: ${RESOURCE_IDENTIFIER}

---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: "${KUBERNETES_VERSION:=v1.23.0}"
  machineTemplate:
    infrastructureRef:
      kind: VpsieMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      name: "${CLUSTER_NAME}-control-plane"
  kubeadmConfigSpec:
    initConfiguration:
        nodeRegistration:
            name: '{{ ds.meta_data["local_hostname"] }}'
            kubeletExtraArgs:
              cloud-provider: vpsie
    clusterConfiguration:
        controllerManager:
            extraArgs: { enable-hostpath-provisioner: 'true' }
    joinConfiguration:
        nodeRegistration:
            name: '{{ ds.meta_data["local_hostname"] }}'
            kubeletExtraArgs:
              cloud-provider: vpsie

---
kind: VpsieMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      vpsiePlan: "${VPSIE_CONTROL_PLANE_MACHINE_TYPE}"
      osIdentifier: "${VPSIE_CONTROL_PLANE_MACHINE_OS}"

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION:=v1.23.0}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: VpsieMachineTemplate

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VpsieMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      vpsiePlan: "${VPSIE_CONTROL_PLANE_MACHINE_TYPE}"
      osIdentifier: "${VPSIE_CONTROL_PLANE_MACHINE_OS}"

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data["local_hostname"] }}'
          kubeletExtraArgs:
            cloud-provider: vpsie